#pragma once

#include <cstdint>

namespace CloverPic::Core {

enum class AppCommand : uint32_t {
    None,
    GoHome,
    ShowNewCanvasModal,
    ShowSettingsModal,
    CreateCanvasFromForm,
    SwapCanvasOrientation,
    ToggleCanvasTransparency,
    SelectRgbProfile,
    SelectCmykProfile,
    SetSettingsCategory,
    ApplySettings,
    SaveSettings,
    CreateCanvasPreset,
    SetCanvasAnchor,
    CloseModal,
    OpenProject,
    OpenRecentProject,
    FocusHomeSearch,
    ShowFiltersModal,
    ShowTextLayerModal,
    SaveProject,
    SaveProjectAs,
    ExportPng,
    Undo,
    Redo,
    ShowCanvasSizeModal,
    FlipLayerHorizontal,
    FlipLayerVertical,
    RotateLayerLeft,
    RotateLayerRight,
    SelectAll,
    ClearSelection,
    InvertSelection,
    Quit,
    SelectTool,
    SetColor,
    AddLayer,
    DeleteLayer,
    ToggleLayerVisibility,
    ToggleLayerLock,
    ToggleProtectAlpha,
    ToggleSolo,
    DuplicateLayer,
    MergeLayerDown,
    SetLayerOpacity,
    SetBlendMode,
    SelectLayer,
    SetBrushParam,
    SetBrushTip,
    SetBrushPreset,
    ApplyFilter,
    CreateTextLayer,
    SetZoomPreset,
    ZoomIn,
    ZoomOut,
    FitCanvas,
    ResetView,
    ToggleViewOption,
    SetSnapMode,
    TogglePanel,
    ToggleLeftSidebar,
    ToggleRightSidebar,
    InitializeLayout,
    ShowUnavailable,
    CloseWorkspace
};

} // namespace CloverPic::Core
